# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"F\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\x12\x11\n\tplatforms\x18\x03 \x03(\t\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xc1\x01\n\x0eSearchResponse\x12\x1f\n\x07results\x18\x01 \x03(\x0b\x32\x0e.search.Result\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x12\x19\n\x11platforms_success\x18\x03 \x03(\t\x12\x19\n\x11platforms_timeout\x18\x04 \x03(\t\x12\x17\n\x0fplatforms_error\x18\x05 \x03(\t\x12*\n\x08metadata\x18\x06 \x01(\x0b\x32\x18.search.ResponseMetadata\"\xbb\x01\n\x06Result\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07snippet\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12.\n\x08metadata\x18\x06 \x03(\x0b\x32\x1c.search.Result.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"G\n\x10ResponseMetadata\x12\x18\n\x10response_time_ms\x18\x01 \x01(\x05\x12\x19\n\x11platforms_queried\x18\x02 \x01(\x05\"I\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x99\x01\n\rSearchService\x12@\n\x0f\x46\x65\x64\x65ratedSearch\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12\x46\n\x0bHealthCheck\x12\x1a.search.HealthCheckRequest\x1a\x1b.search.HealthCheckResponseB+Z)github.com/farhapartex/search-proxy/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/farhapartex/search-proxy/proto'
  _globals['_RESULT_METADATAENTRY']._loaded_options = None
  _globals['_RESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=24
  _globals['_SEARCHREQUEST']._serialized_end=94
  _globals['_HEALTHCHECKREQUEST']._serialized_start=96
  _globals['_HEALTHCHECKREQUEST']._serialized_end=133
  _globals['_SEARCHRESPONSE']._serialized_start=136
  _globals['_SEARCHRESPONSE']._serialized_end=329
  _globals['_RESULT']._serialized_start=332
  _globals['_RESULT']._serialized_end=519
  _globals['_RESULT_METADATAENTRY']._serialized_start=472
  _globals['_RESULT_METADATAENTRY']._serialized_end=519
  _globals['_RESPONSEMETADATA']._serialized_start=521
  _globals['_RESPONSEMETADATA']._serialized_end=592
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=594
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=667
  _globals['_SEARCHSERVICE']._serialized_start=670
  _globals['_SEARCHSERVICE']._serialized_end=823
# @@protoc_insertion_point(module_scope)
